baseurl = "https://darjun.github.io"
title = "Darjun Blog"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = "darjun-blog"
googleAnalytics = "UA-136116022-1"
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "img/home-bg.jpg"
  SEOTitle = "大俊的博客 | Darjun Blog"
  description = "李大俊，程序员, 游戏开发者，热爱游戏，热爱编程。"
  keyword = "李大俊, lidajun, leedarjun, , 李大俊的网络日志, 李大俊的博客, Darjun Blog, 博客, 个人网站, 互联网, Golang, JavaScript, Java, C++"
  slogan = "不积跬步 无以至千里"

  image_404 = "img/404-bg.jpg"
  title_404 = "你来到了没有知识的荒原 :("

  # leancloud storage for page view counter
  page_view_conter = true 
  leancloud_app_id = "TXNGsfsFQyzdASwAnCBlyIkr-gzGzoHsz"
  leancloud_app_key = "5N0H4PYj0GcbhLqSMLfPMf8t"

  # algolia site search
  algolia_search = true
  algolia_appId = "0BP9H8JW2T"
  algolia_indexName = "darjun.github.io"
  algolia_apiKey = "7798d3ae0c79593babd8cd31b9e2f9ad"

  # Sidebar settings
  sidebar_about_description = "Game Developer"
  #sidebar_avatar = "img/avatar-darjun.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`
  sidebar_avatar = "img/darjun.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 2 

  # Baidu Analytics
  ba_track_id = "22b47f8b144298dc77b2beb696c6353d"
  
  # We need a proxy to access Disqus api in China
  # disqus_proxy = "https://disqusapi.leedarjun.com"
  # disqus_site = "https://darjun.github.io"

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles 
  reward = true 
  # reward_guide = "如果这篇文章对你有用,请随意打赏" 

  friends = true
  bookmarks = true
  about_me = true

  [params.social]
  rss            = true 
  email          = "leedarjun@gmail.com"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "full profile url in twitter"
  #linkedin       = "https://www.linkedin.com/in/zhaohuabing"
  #stackoverflow  = "https://stackoverflow.com/users/2306565/huabing-zhao"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/darjun"
  wechat         = "https://darjun.github.io/img/wechat_qrcode.jpg"
  medium         = "https://medium.com/@leedarjun"
  #pinterest     = "full profile url in pinterest"
  
  #[[params.friend_link]]
  #title = "Linda的博客"
  #href =  "https://zhaozhihan.com"

  #[[params.bookmark_link]]
  #title =  "Martin Fowler"
  #href =  "https://martinfowler.com"
  #[[params.bookmark_link]]
  #title = "ServiceMesher"
  #href =  "http://www.servicemesher.com"
  #[[params.bookmark_link]]
  #title = "Awesome Service Mesh"
  #href = "https://servicemesh.gitbooks.io/awesome-servicemesh"
  #[[params.bookmark_link]]
  #title =  "Image Compression"
  #href = "https://tinypng.com"
  #[[params.bookmark_link]]
  #title =  "Pxhere"
  #href = "https://pxhere.com"
  #[[params.bookmark_link]]
  #title = "unsplash"
  #href = "https://unsplash.com"
  
  [[params.addtional_menus]]
  title =  "BOOKS"
  href =  "/top/books/"
  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/top/about/"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 
